INSERT INTO comptable_menu (id, name, icon, url, "order", parent_id) VALUES (1, 'Vue globale', 'fab fa-dashcube', '', 1, null);
INSERT INTO comptable_menu (id, name, icon, url, "order", parent_id) VALUES (2, 'Grand livre', 'fas fa-book', 'grand_livre/', 3, null);
INSERT INTO comptable_menu (id, name, icon, url, "order", parent_id) VALUES (3, 'Journal', 'fas fa-newspaper', null, 4, null);
INSERT INTO comptable_menu (id, name, icon, url, "order", parent_id) VALUES (4, 'Ecriture', 'fas fa-feather-alt', 'journal/choix', 1, 3);
INSERT INTO comptable_menu (id, name, icon, url, "order", parent_id) VALUES (5, 'Type', 'fas fa-th', 'journal/lister', 2, 3);
INSERT INTO comptable_menu (id, name, icon, url, "order", parent_id) VALUES (6, 'Plan Comptable', 'fas fa-code-branch', null, 5, null);
INSERT INTO comptable_menu (id, name, icon, url, "order", parent_id) VALUES (7, 'Compte général', 'fas fa-globe-africa', 'compte_general/lister', 1, 6);
INSERT INTO comptable_menu (id, name, icon, url, "order", parent_id) VALUES (8, 'Compte tiers', 'fas fa-network-wired', 'compte_tiers/lister', 2, 6);
INSERT INTO comptable_menu (id, name, icon, url, "order", parent_id) VALUES (9, 'Divers', 'fas fa-cogs', null, 6, null);
INSERT INTO comptable_menu (id, name, icon, url, "order", parent_id) VALUES (10, 'Devise', 'fas fa-money-bill-wave', 'devise/lister', 1, 9);
INSERT INTO comptable_menu (id, name, icon, url, "order", parent_id) VALUES (11, 'Devise équivalente', 'fas fa-coins', 'devise_equivalente/lister', 2, 9);
INSERT INTO comptable_menu (id, name, icon, url, "order", parent_id) VALUES (12, 'Historique Société', 'fas fa-landmark', 'societe/', 4, 9);
INSERT INTO comptable_menu (id, name, icon, url, "order", parent_id) VALUES (13, 'Balance', 'fas fa-balance-scale', 'balance/', 2, null);
INSERT INTO comptable_menu (id, name, icon, url, "order", parent_id) VALUES (14, 'Pièce', 'fas fa-puzzle-piece', 'piece/lister', 3, 3);
INSERT INTO comptable_menu (id, name, icon, url, "order", parent_id) VALUES (15, 'Exercice', 'fas fa-hourglass-half', 'exercice/lister', 3, 3);
INSERT INTO comptable_menu (id, name, icon, url, "order", parent_id) VALUES (16, 'Status d''entreprise', 'fas fa-gavel', 'status/lister', 3, 9);

INSERT INTO comptable_statusentreprise (id, nom, sigle) VALUES (1, 'Société Anonyme', 'SA');

INSERT INTO comptable_devise (id, code, nom) VALUES (1, 'MGA', 'Ariary');
INSERT INTO comptable_devise (id, code, nom) VALUES (2, 'EUR', 'Euro');
INSERT INTO comptable_devise (id, code, nom) VALUES (3, 'USD', 'Dollar');

INSERT INTO comptable_historiquesociete (id, nom, logo, objectif, siege, date_creation, nif, scan_nif, stat, scan_stat, reg_commerce, scan_reg_commerce, date_information, devise_compte_id, status_entreprise_id) VALUES (1, 'Dimpex', 'logo.png', 'La DIMPEX  (Dago Import Export) a pour objet social la production d''articles industriels et la vente de marchandises auprès de ces clients locaux et étrangers', 'ENCEINTE ITU ANDOHARANOFOTSY BP 1960 Antananarivo 101', '1672531200000', 'NIF-1234', '', 'STAT-1234', '', 'REG-1234', '', '1680566400000', 1, 1);

INSERT INTO comptable_ecriturejournal (date, intitule, debit, credit, compte_general_id, compte_tiers_id, devise_id, journal_id, piece_id, exercice_id) VALUES ('2023-01-01', 'A NOUVEAU 2022', 0, 1400000, 3, null, 1, 2, 16, 4);
INSERT INTO comptable_ecriturejournal (date, intitule, debit, credit, compte_general_id, compte_tiers_id, devise_id, journal_id, piece_id, exercice_id) VALUES ('2023-01-01', 'A NOUVEAU 2022', 0, 27920, 4, null, 1, 2, 16, 4);
INSERT INTO comptable_ecriturejournal (date, intitule, debit, credit, compte_general_id, compte_tiers_id, devise_id, journal_id, piece_id, exercice_id) VALUES ('2023-01-01', 'A NOUVEAU 2022', 0, 177080, 5, null, 1, 2, 16, 4);
INSERT INTO comptable_ecriturejournal (date, intitule, debit, credit, compte_general_id, compte_tiers_id, devise_id, journal_id, piece_id, exercice_id) VALUES ('2023-01-01', 'A NOUVEAU 2022', 0, 322480, 9, null, 1, 2, 16, 4);
INSERT INTO comptable_ecriturejournal (date, intitule, debit, credit, compte_general_id, compte_tiers_id, devise_id, journal_id, piece_id, exercice_id) VALUES ('2023-01-01', 'A NOUVEAU 2022', 0, 1819280, 11, null, 1, 2, 16, 4);
INSERT INTO comptable_ecriturejournal (date, intitule, debit, credit, compte_general_id, compte_tiers_id, devise_id, journal_id, piece_id, exercice_id) VALUES ('2023-01-01', 'A NOUVEAU 2022', 0, 180720, 12, null, 1, 2, 16, 4);
INSERT INTO comptable_ecriturejournal (date, intitule, debit, credit, compte_general_id, compte_tiers_id, devise_id, journal_id, piece_id, exercice_id) VALUES ('2023-01-01', 'A NOUVEAU 2022', 71600, 0, 13, null, 1, 2, 16, 4);
INSERT INTO comptable_ecriturejournal (date, intitule, debit, credit, compte_general_id, compte_tiers_id, devise_id, journal_id, piece_id, exercice_id) VALUES ('2023-01-01', 'A NOUVEAU 2022', 86500, 0, 14, null, 1, 2, 16, 4);
INSERT INTO comptable_ecriturejournal (date, intitule, debit, credit, compte_general_id, compte_tiers_id, devise_id, journal_id, piece_id, exercice_id) VALUES ('2023-01-01', 'A NOUVEAU 2022', 450000, 0, 15, null, 1, 2, 16, 4);
INSERT INTO comptable_ecriturejournal (date, intitule, debit, credit, compte_general_id, compte_tiers_id, devise_id, journal_id, piece_id, exercice_id) VALUES ('2023-01-01', 'A NOUVEAU 2022', 846200, 0, 16, null, 1, 2, 16, 4);
INSERT INTO comptable_ecriturejournal (date, intitule, debit, credit, compte_general_id, compte_tiers_id, devise_id, journal_id, piece_id, exercice_id) VALUES ('2023-01-01', 'A NOUVEAU 2022', 1265500, 0, 17, null, 1, 2, 16, 4);
INSERT INTO comptable_ecriturejournal (date, intitule, debit, credit, compte_general_id, compte_tiers_id, devise_id, journal_id, piece_id, exercice_id) VALUES ('2023-01-01', 'A NOUVEAU 2022', 1346400, 0, 18, null, 1, 2, 16, 4);
INSERT INTO comptable_ecriturejournal (date, intitule, debit, credit, compte_general_id, compte_tiers_id, devise_id, journal_id, piece_id, exercice_id) VALUES ('2023-01-01', 'A NOUVEAU 2022', 783800, 0, 21, null, 1, 2, 16, 4);
INSERT INTO comptable_ecriturejournal (date, intitule, debit, credit, compte_general_id, compte_tiers_id, devise_id, journal_id, piece_id, exercice_id) VALUES ('2023-01-01', 'A NOUVEAU 2022', 121800, 0, 24, null, 1, 2, 16, 4);
INSERT INTO comptable_ecriturejournal (date, intitule, debit, credit, compte_general_id, compte_tiers_id, devise_id, journal_id, piece_id, exercice_id) VALUES ('2023-01-01', 'A NOUVEAU 2022', 120000, 0, 25, null, 1, 2, 16, 4);
INSERT INTO comptable_ecriturejournal (date, intitule, debit, credit, compte_general_id, compte_tiers_id, devise_id, journal_id, piece_id, exercice_id) VALUES ('2023-01-01', 'A NOUVEAU 2022', 0, 94500, 26, null, 1, 2, 16, 4);
INSERT INTO comptable_ecriturejournal (date, intitule, debit, credit, compte_general_id, compte_tiers_id, devise_id, journal_id, piece_id, exercice_id) VALUES ('2023-01-01', 'A NOUVEAU 2022', 0, 186600, 27, null, 1, 2, 16, 4);
INSERT INTO comptable_ecriturejournal (date, intitule, debit, credit, compte_general_id, compte_tiers_id, devise_id, journal_id, piece_id, exercice_id) VALUES ('2023-01-01', 'A NOUVEAU 2022', 0, 597250, 28, null, 1, 2, 16, 4);
INSERT INTO comptable_ecriturejournal (date, intitule, debit, credit, compte_general_id, compte_tiers_id, devise_id, journal_id, piece_id, exercice_id) VALUES ('2023-01-01', 'A NOUVEAU 2022', 0, 681480, 29, null, 1, 2, 16, 4);
INSERT INTO comptable_ecriturejournal (date, intitule, debit, credit, compte_general_id, compte_tiers_id, devise_id, journal_id, piece_id, exercice_id) VALUES ('2023-01-01', 'A NOUVEAU 2022', 0, 459660, 33, null, 1, 2, 16, 4);
INSERT INTO comptable_ecriturejournal (date, intitule, debit, credit, compte_general_id, compte_tiers_id, devise_id, journal_id, piece_id, exercice_id) VALUES ('2023-01-01', 'A NOUVEAU 2022', 276130, 0, 34, null, 1, 2, 16, 4);
INSERT INTO comptable_ecriturejournal (date, intitule, debit, credit, compte_general_id, compte_tiers_id, devise_id, journal_id, piece_id, exercice_id) VALUES ('2023-01-01', 'A NOUVEAU 2022', 1075600, 0, 35, null, 1, 2, 16, 4);
INSERT INTO comptable_ecriturejournal (date, intitule, debit, credit, compte_general_id, compte_tiers_id, devise_id, journal_id, piece_id, exercice_id) VALUES ('2023-01-01', 'A NOUVEAU 2022', 1173180, 0, 36, null, 1, 2, 16, 4);
INSERT INTO comptable_ecriturejournal (date, intitule, debit, credit, compte_general_id, compte_tiers_id, devise_id, journal_id, piece_id, exercice_id) VALUES ('2023-01-01', 'A NOUVEAU 2022', 0, 346580, 37, null, 1, 2, 16, 4);
INSERT INTO comptable_ecriturejournal (date, intitule, debit, credit, compte_general_id, compte_tiers_id, devise_id, journal_id, piece_id, exercice_id) VALUES ('2023-01-01', 'A NOUVEAU 2022', 0, 865400, 38, 4, 1, 2, 16, 4);
INSERT INTO comptable_ecriturejournal (date, intitule, debit, credit, compte_general_id, compte_tiers_id, devise_id, journal_id, piece_id, exercice_id) VALUES ('2023-01-01', 'A NOUVEAU 2022', 0, 1236300, 38, 5, 1, 2, 16, 4);
INSERT INTO comptable_ecriturejournal (date, intitule, debit, credit, compte_general_id, compte_tiers_id, devise_id, journal_id, piece_id, exercice_id) VALUES ('2023-01-01', 'A NOUVEAU 2022', 0, 748000, 38, 6, 1, 2, 16, 4);
INSERT INTO comptable_ecriturejournal (date, intitule, debit, credit, compte_general_id, compte_tiers_id, devise_id, journal_id, piece_id, exercice_id) VALUES ('2023-01-01', 'A NOUVEAU 2022', 0, 750850, 38, 7, 1, 2, 16, 4);
INSERT INTO comptable_ecriturejournal (date, intitule, debit, credit, compte_general_id, compte_tiers_id, devise_id, journal_id, piece_id, exercice_id) VALUES ('2023-01-01', 'A NOUVEAU 2022', 0, 288650, 41, null, 1, 2, 16, 4);
INSERT INTO comptable_ecriturejournal (date, intitule, debit, credit, compte_general_id, compte_tiers_id, devise_id, journal_id, piece_id, exercice_id) VALUES ('2023-01-01', 'A NOUVEAU 2022', 26450, 0, 43, null, 1, 2, 16, 4);
INSERT INTO comptable_ecriturejournal (date, intitule, debit, credit, compte_general_id, compte_tiers_id, devise_id, journal_id, piece_id, exercice_id) VALUES ('2023-01-01', 'A NOUVEAU 2022', 418000, 0, 44, 8, 1, 2, 16, 4);
INSERT INTO comptable_ecriturejournal (date, intitule, debit, credit, compte_general_id, compte_tiers_id, devise_id, journal_id, piece_id, exercice_id) VALUES ('2023-01-01', 'A NOUVEAU 2022', 1012500, 0, 44, 9, 1, 2, 16, 4);
INSERT INTO comptable_ecriturejournal (date, intitule, debit, credit, compte_general_id, compte_tiers_id, devise_id, journal_id, piece_id, exercice_id) VALUES ('2023-01-01', 'A NOUVEAU 2022', 852900, 0, 44, 10, 1, 2, 16, 4);
INSERT INTO comptable_ecriturejournal (date, intitule, debit, credit, compte_general_id, compte_tiers_id, devise_id, journal_id, piece_id, exercice_id) VALUES ('2023-01-01', 'A NOUVEAU 2022', 720000, 0, 45, null, 1, 2, 16, 4);
INSERT INTO comptable_ecriturejournal (date, intitule, debit, credit, compte_general_id, compte_tiers_id, devise_id, journal_id, piece_id, exercice_id) VALUES ('2023-01-01', 'A NOUVEAU 2022', 160000, 0, 46, null, 1, 2, 16, 4);
INSERT INTO comptable_ecriturejournal (date, intitule, debit, credit, compte_general_id, compte_tiers_id, devise_id, journal_id, piece_id, exercice_id) VALUES ('2023-01-01', 'A NOUVEAU 2022', 57500, 0, 47, null, 1, 2, 16, 4);
INSERT INTO comptable_ecriturejournal (date, intitule, debit, credit, compte_general_id, compte_tiers_id, devise_id, journal_id, piece_id, exercice_id) VALUES ('2023-01-01', 'A NOUVEAU 2022', 0, 455560, 48, null, 1, 2, 16, 4);
INSERT INTO comptable_ecriturejournal (date, intitule, debit, credit, compte_general_id, compte_tiers_id, devise_id, journal_id, piece_id, exercice_id) VALUES ('2023-01-01', 'A NOUVEAU 2022', 0, 42380, 52, null, 1, 2, 16, 4);
INSERT INTO comptable_ecriturejournal (date, intitule, debit, credit, compte_general_id, compte_tiers_id, devise_id, journal_id, piece_id, exercice_id) VALUES ('2023-01-01', 'A NOUVEAU 2022', 0, 28260, 53, null, 1, 2, 16, 4);
INSERT INTO comptable_ecriturejournal (date, intitule, debit, credit, compte_general_id, compte_tiers_id, devise_id, journal_id, piece_id, exercice_id) VALUES ('2023-01-01', 'A NOUVEAU 2022', 0, 270000, 54, null, 1, 2, 16, 4);
INSERT INTO comptable_ecriturejournal (date, intitule, debit, credit, compte_general_id, compte_tiers_id, devise_id, journal_id, piece_id, exercice_id) VALUES ('2023-01-01', 'A NOUVEAU 2022', 0, 203370, 58, null, 1, 2, 16, 4);
INSERT INTO comptable_ecriturejournal (date, intitule, debit, credit, compte_general_id, compte_tiers_id, devise_id, journal_id, piece_id, exercice_id) VALUES ('2023-01-01', 'A NOUVEAU 2022', 26700, 0, 60, null, 1, 2, 16, 4);
INSERT INTO comptable_ecriturejournal (date, intitule, debit, credit, compte_general_id, compte_tiers_id, devise_id, journal_id, piece_id, exercice_id) VALUES ('2023-01-01', 'A NOUVEAU 2022', 172500, 0, 62, null, 1, 2, 16, 4);
INSERT INTO comptable_ecriturejournal (date, intitule, debit, credit, compte_general_id, compte_tiers_id, devise_id, journal_id, piece_id, exercice_id) VALUES ('2023-01-01', 'A NOUVEAU 2022', 0, 80000, 65, null, 1, 2, 16, 4);
INSERT INTO comptable_ecriturejournal (date, intitule, debit, credit, compte_general_id, compte_tiers_id, devise_id, journal_id, piece_id, exercice_id) VALUES ('2023-01-01', 'A NOUVEAU 2022', 300300, 0, 66, null, 1, 2, 16, 4);
INSERT INTO comptable_ecriturejournal (date, intitule, debit, credit, compte_general_id, compte_tiers_id, devise_id, journal_id, piece_id, exercice_id) VALUES ('2023-01-01', 'A NOUVEAU 2022', 0, 119560, 68, null, 1, 2, 16, 4);
INSERT INTO comptable_ecriturejournal (date, intitule, debit, credit, compte_general_id, compte_tiers_id, devise_id, journal_id, piece_id, exercice_id) VALUES ('2023-01-01', 'A NOUVEAU 2022', 18320, 0, 70, null, 1, 2, 16, 4);
