# Generated by Django 4.2.1 on 2023-05-06 11:08

import comptable.models.historique_societe
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompteGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True)),
                ('intitule', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Compte général',
                'verbose_name_plural': 'Comptes généraux',
            },
        ),
        migrations.CreateModel(
            name='CompteTiers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=13, unique=True)),
                ('intitule', models.CharField(max_length=100)),
                ('compte_general', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comptable.comptegeneral')),
            ],
            options={
                'verbose_name': 'Compte tiers',
                'verbose_name_plural': 'Comptes tiers',
            },
        ),
        migrations.CreateModel(
            name='Devise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('nom', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Devise',
                'verbose_name_plural': 'Devises',
            },
        ),
        migrations.CreateModel(
            name='Exercice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debut', models.DateField()),
                ('fin', models.DateField()),
                ('cloture', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='fas fa-question-circle', max_length=100, null=True)),
                ('color', models.CharField(default='secondary', max_length=100, null=True)),
                ('code', models.CharField(max_length=2, unique=True, validators=[django.core.validators.MinLengthValidator(2)])),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=100)),
                ('content', models.CharField(blank=True, max_length=1000)),
                ('color', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='StatusEntreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('sigle', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('fichier', models.FileField(blank=True, default=None, null=True, upload_to='pieces/')),
                ('prefixe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comptable.journal')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.CharField(blank=True, max_length=100, null=True)),
                ('order', models.IntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='comptable.menu')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueSociete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='societe/')),
                ('objectif', models.CharField(max_length=255)),
                ('siege', models.CharField(max_length=100)),
                ('date_creation', models.DateField(validators=[comptable.models.historique_societe.validate_date_not_in_future])),
                ('nif', models.CharField(max_length=20)),
                ('scan_nif', models.FileField(upload_to='societe/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'png', 'jpg', 'jpeg'])])),
                ('stat', models.CharField(max_length=20)),
                ('scan_stat', models.FileField(upload_to='societe/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'png', 'jpg', 'jpeg'])])),
                ('reg_commerce', models.CharField(max_length=20)),
                ('scan_reg_commerce', models.FileField(upload_to='societe/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'png', 'jpg', 'jpeg'])])),
                ('date_information', models.DateTimeField(auto_now_add=True)),
                ('devise_compte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comptable.devise')),
                ('status_entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comptable.statusentreprise')),
            ],
        ),
        migrations.CreateModel(
            name='EcritureJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('intitule', models.CharField(max_length=100)),
                ('debit', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20)),
                ('credit', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20)),
                ('valide', models.DateField(null=True)),
                ('compte_general', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comptable.comptegeneral')),
                ('compte_tiers', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='comptable.comptetiers')),
                ('devise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comptable.devise')),
                ('exercice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comptable.exercice')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comptable.journal')),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comptable.piece')),
            ],
        ),
        migrations.CreateModel(
            name='DeviseEquivalente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taux', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('devise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comptable.devise')),
                ('devise_equivalente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devise_equivalente', to='comptable.devise')),
            ],
            options={
                'verbose_name': 'Devise Equivalente',
                'verbose_name_plural': 'Devises Equivalente',
            },
        ),
    ]
