# Generated by Django 4.2.1 on 2023-05-06 11:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiquesociete',
            name='logo',
            field=models.ImageField(upload_to='societe/logo/'),
        ),
        migrations.AlterField(
            model_name='historiquesociete',
            name='scan_nif',
            field=models.FileField(upload_to='societe/scan_nif/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'png', 'jpg', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='historiquesociete',
            name='scan_reg_commerce',
            field=models.FileField(upload_to='societe/scan_reg_commerce/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'png', 'jpg', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='historiquesociete',
            name='scan_stat',
            field=models.FileField(upload_to='societe/scan_stat/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'png', 'jpg', 'jpeg'])]),
        ),
    ]
