--- Menu ---
INSERT INTO comptable_menu (name, icon, url, "order", parent_id) VALUES ('Vue globale', 'fab fa-dashcube', '', 1, null);
INSERT INTO comptable_menu (name, icon, url, "order", parent_id) VALUES ('Grand livre', 'fas fa-book', 'grand_livre/', 4, null);
INSERT INTO comptable_menu (name, icon, url, "order", parent_id) VALUES ('Journal', 'fas fa-newspaper', null, 5, null);
INSERT INTO comptable_menu (name, icon, url, "order", parent_id) VALUES ('Ecriture', 'fas fa-feather-alt', 'journal/choix', 1, 3);
INSERT INTO comptable_menu (name, icon, url, "order", parent_id) VALUES ('Type', 'fas fa-th', 'journal/lister', 2, 3);
INSERT INTO comptable_menu (name, icon, url, "order", parent_id) VALUES ('Plan Comptable', 'fas fa-code-branch', null, 6, null);
INSERT INTO comptable_menu (name, icon, url, "order", parent_id) VALUES ('Compte général', 'fas fa-globe-africa', 'compte_general/lister', 1, 6);
INSERT INTO comptable_menu (name, icon, url, "order", parent_id) VALUES ('Compte tiers', 'fas fa-network-wired', 'compte_tiers/lister', 2, 6);
INSERT INTO comptable_menu (name, icon, url, "order", parent_id) VALUES ('Divers', 'fas fa-cogs', null, 7, null);
INSERT INTO comptable_menu (name, icon, url, "order", parent_id) VALUES ('Devise', 'fas fa-money-bill-wave', 'devise/lister', 1, 9);
INSERT INTO comptable_menu (name, icon, url, "order", parent_id) VALUES ('Devise équivalente', 'fas fa-coins', 'devise_equivalente/lister', 2, 9);
INSERT INTO comptable_menu (name, icon, url, "order", parent_id) VALUES ('Historique Société', 'fas fa-landmark', 'historique/', 4, 9);
INSERT INTO comptable_menu (name, icon, url, "order", parent_id) VALUES ('Balance', 'fas fa-balance-scale', 'balance/', 3, null);
INSERT INTO comptable_menu (name, icon, url, "order", parent_id) VALUES ('Pièce', 'fas fa-puzzle-piece', 'piece/lister', 3, 3);
INSERT INTO comptable_menu (name, icon, url, "order", parent_id) VALUES ('Exercice', 'fas fa-hourglass-half', 'self/lister', 3, 3);
INSERT INTO comptable_menu (name, icon, url, "order", parent_id) VALUES ('Status d''entreprise', 'fas fa-gavel', 'status_entreprise/lister', 3, 9);
INSERT INTO comptable_menu (name, icon, url, "order", parent_id) VALUES ('Etat financier', 'fas fa-chart-line', null, 2, null);
INSERT INTO comptable_menu (name, icon, url, "order", parent_id) VALUES ('Actif', 'fas fa-laptop-house', 'etat_financier/actif', 1, 17);

-- Status entreprise --
INSERT INTO comptable_statusentreprise (id, nom, sigle) VALUES (1, 'Société Anonyme', 'SA');

-- Devise --
INSERT INTO comptable_devise (id, code, nom) VALUES (1, 'MGA', 'Ariary');
INSERT INTO comptable_devise (id, code, nom) VALUES (2, 'EUR', 'Euro');
INSERT INTO comptable_devise (id, code, nom) VALUES (3, 'USD', 'Dollar');

-- Historique société --
INSERT INTO comptable_historiquesociete (id, nom, logo, objectif, siege, date_creation, nif, scan_nif, stat, scan_stat, reg_commerce, scan_reg_commerce, date_information, devise_compte_id, status_entreprise_id) VALUES
    (1, 'Dimpex', 'logo.png',
     'La DIMPEX  (Dago Import Export) a pour objet social la production d''articles industriels et la vente de marchandises auprès de ces clients locaux et étrangers',
     'ENCEINTE ITU ANDOHARANOFOTSY BP 1960 Antananarivo 101', '2023-01-01', 'NIF-1234', '', 'STAT-1234', '', 'REG-1234', '', '2023-01-01', 1, 1);

-- Exercice --
INSERT INTO comptable_exercice (id, debut, fin) VALUES (1, '2023-01-01', '2023-12-31');

-- Journal --
INSERT INTO comptable_journal (icon, color, code, nom) VALUES ('fas fa-dollar-sign', 'white', 'AC', 'Achat');
INSERT INTO comptable_journal (icon, color, code, nom) VALUES ('fas fa-recycle', 'success', 'AN', 'A nouveau');
INSERT INTO comptable_journal (icon, color, code, nom) VALUES ('fas fa-landmark', 'primary', 'BN', 'Banque BNI');
INSERT INTO comptable_journal (icon, color, code, nom) VALUES ('fas fa-landmark', 'green', 'BO', 'Banque BOA');
INSERT INTO comptable_journal (icon, color, code, nom) VALUES ('fas fa-cash-register', 'info', 'CA', 'Caisse');
INSERT INTO comptable_journal (icon, color, code, nom) VALUES ('fas fa-question-circle', 'purple', 'OD', 'Operations diverses');
INSERT INTO comptable_journal (icon, color, code, nom) VALUES ('fas fa-network-wired', 'cyan', 'VL', 'Vente locales');
INSERT INTO comptable_journal (icon, color, code, nom) VALUES ('fas fa-globe', 'pink', 'VE', 'Vente a l''exportation');

-- Compte --
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('10100', 'CAPITAL');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('10610', 'RESERVE LEGALE');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('11000', 'REPORT A NOUVEAU');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('11010', 'REPORT A NOUVEAU SOLDE CREDITEUR');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('11200', 'AUTRES PRODUITS ET CHARGES');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('11900', 'REPORT A NOUVEAU SOLDE DEBITEUR');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('12800', 'RESULTAT EN INSTANCE');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('13300', 'IMPOTS DIFFERES ACTIFS');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('16110', 'EMPRUNT A LT');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('16510', 'ENMPRUNT A MOYEN TERME');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('20124', 'FRAIS DE REHABILITATION');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('20800', 'AUTRES IMMOB INCORPORELLES');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('21100', 'TERRAINS');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('21200', 'CONSTRUCTION');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('21300', 'MATERIEL ET OUTILLAGE');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('21510', 'MATERIEL AUTOMOBILE');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('21520', 'MATERIEL MOTO');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('21600', 'AGENCEMENT. AM .INST');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('21810', 'MATERIELS ET MOBILIERS DE BUREAU');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('21819', 'MATERIELS INFORMATIQUES ET AUTRES');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('21820', 'MAT. MOB DE LOGEMENT');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('21880', 'AUTRES IMMOBILISATIONS CORP');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('23000', 'IMMOBILISATION EN COURS');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('28000', 'AMORT IMMOB INCORP');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('28120', 'AMORTISSEMENT DES CONSTRUCTIONS');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('28130', 'AMORT MACH-MATER-OUTIL');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('28150', 'AMORT MAT DE TRANSPORT');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('28160', 'AMORT A.A.I');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('28181', 'AMORT MATERIEL&MOB');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('28182', 'AMORTISSEMENTS MATERIELS INFORMATIQ');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('28183', 'AMORT MATER & MOB LOGT');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('32110', 'STOCK MATIERES PREMIERES');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('35500', 'STOCK PRODUITS FINIS');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('37000', 'STOCK MARCHANDISES');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('39700', 'PROVISIONS/DEPRECIATIONS STOCKS');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('40110', 'FOURNISSEURS DEXPLOITATIONS LOCAUX');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('40120', 'FOURNISSEURS DEXPLOITATIONS ETRANGERS');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('40310', 'FOURNISSEURS D''IMMOBILISATION');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('40810', 'FRNS: FACTURE A RECEVOIR');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('40910', 'FRNS:AVANCES&ACOMPTES VERSER');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('40980', 'FRNS: RABAIS A OBTENIR');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('41110', 'CLIENTS LOCAUX');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('41120', 'CLIENTS ETRANGERS');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('41400', 'CLIENTS DOUTEUX');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('41800', 'CLIENTS FACTURE A RETABLIR');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('42100', 'PERSONNEL: SALAIRES A PAYER');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('42510', 'PERSONNEL: AVANCES QUINZAINES');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('42520', 'PERSONNEL: AVANCES SPECIALES');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('42860', 'PERS:CHARGES  A PAYER');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('43100', 'CNAPS ');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('43120', 'OSTIE');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('44200', 'ETAT IBS');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('44210', 'ACOMPTE IBS');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('44321', 'TVA … IMPUTER:DEC ULTERIEURE');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('44500', 'ETAT:IRSA VERSER');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('44560', 'ETAT: TVA DEDUCTIBLE');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('44570', 'ETAT: TVA COLLECTEE');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('44571', 'TVA A VERSER');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('45100', 'COMPTE  COURANT ASSOC');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('46700', 'DEB/CRED DIVERS');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('46800', 'CHARGES A PAYER DEB/CRED DIVERS');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('48610', 'CHARGE CONSTATES D''AVANCE');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('49100', 'PERTE/CLIENTS');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('51200', 'BOA ANKORONDRANO');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('51201', 'BOA DOLLARS');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('51202', 'BNI MADAGASCAR');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('51203', 'BNI DOLLARS');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('53100', 'CAISSE ');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('58110', 'VIREMENTINTERNE:BANQ/CAISSE');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('58130', 'VIREMENT INTERNE:BANQ/BANQ');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('58140', 'VIREMENT INTERNE CAISSE/CAISSE');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('60100', 'ACHAT MATIERES PREMIERESS');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('60200', 'FOURNIT DE MAGASIN');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('60210', 'FOURNIT BUR ');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('60220', 'FOURNIT DE LOGT');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('60230', 'EMBALLAGES(PLAST-CARTON....');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('60240', 'PIEC RECH VOITURES ADMINISTRATIVES');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('60241', 'PIEC RECH CAMIONS');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('60242', 'PIEC RECH MOTO');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('60250', 'AUTRES ACHATS');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('60300', 'VARIATION  STOCK MAT PREM');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('60610', 'EAU ET ELECTRICITE');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('60620', 'GAZ,COMBUST,CARBURANT,LUBRIF');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('61300', 'LOC IMMOBILIERES');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('61380', 'AUTRES LOCATIONS');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('61550', 'ENTRET & REP VEHICULE');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('61560', 'MAINTENANCE');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('61610', 'ASSURANCE GLOBALE DOMMAGES');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('61611', 'ASSURANCE FLOTTE AUTOMOBILE');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('61800', 'PHOTOCOPIE ET ASSIMILES ');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('61810', 'ENVOI COLIS(LETTRE&DOC...');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('62100', 'PERSONNEL EXTER');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('62210', 'HONORAIRE');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('62220', 'REMUNERATION DES TRANSITAIRES');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('62230', 'CATALOGUES ET IMPRIMES');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('62240', 'PUBLICATION');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('62250', 'SPONSORING-MECENAT...');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('62260', 'TS DOUANE ET ASSIMILES');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('62400', 'FRAIS DE TRANSPORT');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('62510', 'VOYAGES   ET DEPLACEMENT');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('62520', 'MISSION(DEPL+HEBERGT+RESTø)');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('62530', 'RECEPTION');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('62610', 'SERVICES POSTAUX');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('62620', 'TEL&FAX');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('62630', 'INTERNET TANA');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('62740', 'COMMISSIONS BANCAIRE INTERNATIONALE');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('62760', 'COMMISSIONS BNI');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('62770', 'COMMISSIONS BOA');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('62880', 'AUTRES  CHARGES EXTERNES');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('63680', 'AUTRES IMPOTS/TAXES/DROITS DIV');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('64100', 'REMUNERATION PERSONNEL');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('64120', 'DROIT DE CONGES');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('64511', 'CNAPS:COTISATION  PATRONALE');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('64512', 'OSTIE : COTISATION PATRONALE');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('64750', 'MED ET ASSIM PERS');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('65800', 'AUTRES CHARGES DIVERSES');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('65810', 'ECART/PAIEMENT');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('65811', 'PERTE/TVA NON RECUPERABLE');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('66200', 'INTERETS  BANCAIRES BNI');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('66300', 'INTERETS  BANCAIRES BOA');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('66600', 'DIFFF  DE  CHANGE  PERTE');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('66680', 'AGIOS/TRAITES');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('68110', 'D.A.P  IMMO INCORPORELLES');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('68120', 'D.A.P  IMMO  CORPORELLE');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('70110', 'VENTE LOCALE');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('70120', 'VENTES  A  L EXPORTATION');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('70800', 'AUTRES PROD  DES ACT ANNEX&ACS');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('71300', 'VARIATION DE STOCK  P.F');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('75800', 'AUTRES PRODUITS D EXPLOITATION');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('75810', 'ECART/ENCAISSEMENT');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('76200', 'INTERET CREDITEUR BANQUES BNI');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('76300', 'INTERET CREDITEUR BANQUES BOA');
INSERT INTO comptable_comptegeneral (code, intitule) VALUES ('76600', 'DIFFERENCE DE  CHANGE:PROFIT');
INSERT INTO comptable_comptetiers (code, intitule, compte_general_id) VALUES ('RAVINALA', 'RAVINALA', 36);
INSERT INTO comptable_comptetiers (code, intitule, compte_general_id) VALUES ('LOVASOA', 'LOVASOA', 36);
INSERT INTO comptable_comptetiers (code, intitule, compte_general_id) VALUES ('PAPANGO', 'PAPANGO', 36);
INSERT INTO comptable_comptetiers (code, intitule, compte_general_id) VALUES ('ORIMBATO', 'ORIMBATO', 36);
INSERT INTO comptable_comptetiers (code, intitule, compte_general_id) VALUES ('SOLO', 'SOLO', 42);
INSERT INTO comptable_comptetiers (code, intitule, compte_general_id) VALUES ('RABE', 'RABE', 42);
INSERT INTO comptable_comptetiers (code, intitule, compte_general_id) VALUES ('NORO', 'NORO', 42);

-- Piece --
INSERT INTO comptable_piece (numero, prefixe_id) VALUES ('2022', 2);

-- Ecriture --
INSERT INTO comptable_ecriturejournal(date, intitule, debit, credit, compte_general_id, compte_tiers_id, devise_id, journal_id, piece_id, exercice_id) VALUES ('2023-01-01', 'A NOUVEAU 2022', 0, 1400000, 1, null, 1, 2, 1, 1);
INSERT INTO comptable_ecriturejournal(date, intitule, debit, credit, compte_general_id, compte_tiers_id, devise_id, journal_id, piece_id, exercice_id) VALUES ('2023-01-01', 'A NOUVEAU 2022', 0, 27920, 2, null, 1, 2, 1, 1);
INSERT INTO comptable_ecriturejournal(date, intitule, debit, credit, compte_general_id, compte_tiers_id, devise_id, journal_id, piece_id, exercice_id) VALUES ('2023-01-01', 'A NOUVEAU 2022', 0, 177080, 3, null, 1, 2, 1, 1);
INSERT INTO comptable_ecriturejournal(date, intitule, debit, credit, compte_general_id, compte_tiers_id, devise_id, journal_id, piece_id, exercice_id) VALUES ('2023-01-01', 'A NOUVEAU 2022', 0, 322480, 7, null, 1, 2, 1, 1);
INSERT INTO comptable_ecriturejournal(date, intitule, debit, credit, compte_general_id, compte_tiers_id, devise_id, journal_id, piece_id, exercice_id) VALUES ('2023-01-01', 'A NOUVEAU 2022', 0, 1819280, 9, null, 1, 2, 1, 1);
INSERT INTO comptable_ecriturejournal(date, intitule, debit, credit, compte_general_id, compte_tiers_id, devise_id, journal_id, piece_id, exercice_id) VALUES ('2023-01-01', 'A NOUVEAU 2022', 0, 180720, 10, null, 1, 2, 1, 1);
INSERT INTO comptable_ecriturejournal(date, intitule, debit, credit, compte_general_id, compte_tiers_id, devise_id, journal_id, piece_id, exercice_id) VALUES ('2023-01-01', 'A NOUVEAU 2022', 71600, 0, 11, null, 1, 2, 1, 1);
INSERT INTO comptable_ecriturejournal(date, intitule, debit, credit, compte_general_id, compte_tiers_id, devise_id, journal_id, piece_id, exercice_id) VALUES ('2023-01-01', 'A NOUVEAU 2022', 86500, 0, 12, null, 1, 2, 1, 1);
INSERT INTO comptable_ecriturejournal(date, intitule, debit, credit, compte_general_id, compte_tiers_id, devise_id, journal_id, piece_id, exercice_id) VALUES ('2023-01-01', 'A NOUVEAU 2022', 450000, 0, 13, null, 1, 2, 1, 1);
INSERT INTO comptable_ecriturejournal(date, intitule, debit, credit, compte_general_id, compte_tiers_id, devise_id, journal_id, piece_id, exercice_id) VALUES ('2023-01-01', 'A NOUVEAU 2022', 846200, 0, 14, null, 1, 2, 1, 1);
INSERT INTO comptable_ecriturejournal(date, intitule, debit, credit, compte_general_id, compte_tiers_id, devise_id, journal_id, piece_id, exercice_id) VALUES ('2023-01-01', 'A NOUVEAU 2022', 1265500, 0, 15, null, 1, 2, 1, 1);
INSERT INTO comptable_ecriturejournal(date, intitule, debit, credit, compte_general_id, compte_tiers_id, devise_id, journal_id, piece_id, exercice_id) VALUES ('2023-01-01', 'A NOUVEAU 2022', 1346400, 0, 16, null, 1, 2, 1, 1);
INSERT INTO comptable_ecriturejournal(date, intitule, debit, credit, compte_general_id, compte_tiers_id, devise_id, journal_id, piece_id, exercice_id) VALUES ('2023-01-01', 'A NOUVEAU 2022', 783800, 0, 19, null, 1, 2, 1, 1);
INSERT INTO comptable_ecriturejournal(date, intitule, debit, credit, compte_general_id, compte_tiers_id, devise_id, journal_id, piece_id, exercice_id) VALUES ('2023-01-01', 'A NOUVEAU 2022', 121800, 0, 22, null, 1, 2, 1, 1);
INSERT INTO comptable_ecriturejournal(date, intitule, debit, credit, compte_general_id, compte_tiers_id, devise_id, journal_id, piece_id, exercice_id) VALUES ('2023-01-01', 'A NOUVEAU 2022', 120000, 0, 23, null, 1, 2, 1, 1);
INSERT INTO comptable_ecriturejournal(date, intitule, debit, credit, compte_general_id, compte_tiers_id, devise_id, journal_id, piece_id, exercice_id) VALUES ('2023-01-01', 'A NOUVEAU 2022', 0, 94500, 24, null, 1, 2, 1, 1);
INSERT INTO comptable_ecriturejournal(date, intitule, debit, credit, compte_general_id, compte_tiers_id, devise_id, journal_id, piece_id, exercice_id) VALUES ('2023-01-01', 'A NOUVEAU 2022', 0, 186600, 25, null, 1, 2, 1, 1);
INSERT INTO comptable_ecriturejournal(date, intitule, debit, credit, compte_general_id, compte_tiers_id, devise_id, journal_id, piece_id, exercice_id) VALUES ('2023-01-01', 'A NOUVEAU 2022', 0, 597250, 26, null, 1, 2, 1, 1);
INSERT INTO comptable_ecriturejournal(date, intitule, debit, credit, compte_general_id, compte_tiers_id, devise_id, journal_id, piece_id, exercice_id) VALUES ('2023-01-01', 'A NOUVEAU 2022', 0, 681480, 27, null, 1, 2, 1, 1);
INSERT INTO comptable_ecriturejournal(date, intitule, debit, credit, compte_general_id, compte_tiers_id, devise_id, journal_id, piece_id, exercice_id) VALUES ('2023-01-01', 'A NOUVEAU 2022', 0, 459660, 31, null, 1, 2, 1, 1);
INSERT INTO comptable_ecriturejournal(date, intitule, debit, credit, compte_general_id, compte_tiers_id, devise_id, journal_id, piece_id, exercice_id) VALUES ('2023-01-01', 'A NOUVEAU 2022', 276130, 0, 32, null, 1, 2, 1, 1);
INSERT INTO comptable_ecriturejournal(date, intitule, debit, credit, compte_general_id, compte_tiers_id, devise_id, journal_id, piece_id, exercice_id) VALUES ('2023-01-01', 'A NOUVEAU 2022', 1075600, 0, 33, null, 1, 2, 1, 1);
INSERT INTO comptable_ecriturejournal(date, intitule, debit, credit, compte_general_id, compte_tiers_id, devise_id, journal_id, piece_id, exercice_id) VALUES ('2023-01-01', 'A NOUVEAU 2022', 1173180, 0, 34, null, 1, 2, 1, 1);
INSERT INTO comptable_ecriturejournal(date, intitule, debit, credit, compte_general_id, compte_tiers_id, devise_id, journal_id, piece_id, exercice_id) VALUES ('2023-01-01', 'A NOUVEAU 2022', 0, 346580, 35, null, 1, 2, 1, 1);
INSERT INTO comptable_ecriturejournal(date, intitule, debit, credit, compte_general_id, compte_tiers_id, devise_id, journal_id, piece_id, exercice_id) VALUES ('2023-01-01', 'A NOUVEAU 2022', 0, 865400, 36, 1, 1, 2, 1, 1);
INSERT INTO comptable_ecriturejournal(date, intitule, debit, credit, compte_general_id, compte_tiers_id, devise_id, journal_id, piece_id, exercice_id) VALUES ('2023-01-01', 'A NOUVEAU 2022', 0, 1236300, 36, 2, 1, 2, 1, 1);
INSERT INTO comptable_ecriturejournal(date, intitule, debit, credit, compte_general_id, compte_tiers_id, devise_id, journal_id, piece_id, exercice_id) VALUES ('2023-01-01', 'A NOUVEAU 2022', 0, 748000, 36, 3, 1, 2, 1, 1);
INSERT INTO comptable_ecriturejournal(date, intitule, debit, credit, compte_general_id, compte_tiers_id, devise_id, journal_id, piece_id, exercice_id) VALUES ('2023-01-01', 'A NOUVEAU 2022', 0, 750850, 36, 4, 1, 2, 1, 1);
INSERT INTO comptable_ecriturejournal(date, intitule, debit, credit, compte_general_id, compte_tiers_id, devise_id, journal_id, piece_id, exercice_id) VALUES ('2023-01-01', 'A NOUVEAU 2022', 0, 288650, 39, null, 1, 2, 1, 1);
INSERT INTO comptable_ecriturejournal(date, intitule, debit, credit, compte_general_id, compte_tiers_id, devise_id, journal_id, piece_id, exercice_id) VALUES ('2023-01-01', 'A NOUVEAU 2022', 26450, 0, 41, null, 1, 2, 1, 1);
INSERT INTO comptable_ecriturejournal(date, intitule, debit, credit, compte_general_id, compte_tiers_id, devise_id, journal_id, piece_id, exercice_id) VALUES ('2023-01-01', 'A NOUVEAU 2022', 418000, 0, 42, 5, 1, 2, 1, 1);
INSERT INTO comptable_ecriturejournal(date, intitule, debit, credit, compte_general_id, compte_tiers_id, devise_id, journal_id, piece_id, exercice_id) VALUES ('2023-01-01', 'A NOUVEAU 2022', 1012500, 0, 42, 6, 1, 2, 1, 1);
INSERT INTO comptable_ecriturejournal(date, intitule, debit, credit, compte_general_id, compte_tiers_id, devise_id, journal_id, piece_id, exercice_id) VALUES ('2023-01-01', 'A NOUVEAU 2022', 852900, 0, 42, 7, 1, 2, 1, 1);
INSERT INTO comptable_ecriturejournal(date, intitule, debit, credit, compte_general_id, compte_tiers_id, devise_id, journal_id, piece_id, exercice_id) VALUES ('2023-01-01', 'A NOUVEAU 2022', 720000, 0, 43, null, 1, 2, 1, 1);
INSERT INTO comptable_ecriturejournal(date, intitule, debit, credit, compte_general_id, compte_tiers_id, devise_id, journal_id, piece_id, exercice_id) VALUES ('2023-01-01', 'A NOUVEAU 2022', 160000, 0, 44, null, 1, 2, 1, 1);
INSERT INTO comptable_ecriturejournal(date, intitule, debit, credit, compte_general_id, compte_tiers_id, devise_id, journal_id, piece_id, exercice_id) VALUES ('2023-01-01', 'A NOUVEAU 2022', 57500, 0, 45, null, 1, 2, 1, 1);
INSERT INTO comptable_ecriturejournal(date, intitule, debit, credit, compte_general_id, compte_tiers_id, devise_id, journal_id, piece_id, exercice_id) VALUES ('2023-01-01', 'A NOUVEAU 2022', 0, 455560, 46, null, 1, 2, 1, 1);
INSERT INTO comptable_ecriturejournal(date, intitule, debit, credit, compte_general_id, compte_tiers_id, devise_id, journal_id, piece_id, exercice_id) VALUES ('2023-01-01', 'A NOUVEAU 2022', 0, 42380, 50, null, 1, 2, 1, 1);
INSERT INTO comptable_ecriturejournal(date, intitule, debit, credit, compte_general_id, compte_tiers_id, devise_id, journal_id, piece_id, exercice_id) VALUES ('2023-01-01', 'A NOUVEAU 2022', 0, 28260, 51, null, 1, 2, 1, 1);
INSERT INTO comptable_ecriturejournal(date, intitule, debit, credit, compte_general_id, compte_tiers_id, devise_id, journal_id, piece_id, exercice_id) VALUES ('2023-01-01', 'A NOUVEAU 2022', 0, 270000, 52, null, 1, 2, 1, 1);
INSERT INTO comptable_ecriturejournal(date, intitule, debit, credit, compte_general_id, compte_tiers_id, devise_id, journal_id, piece_id, exercice_id) VALUES ('2023-01-01', 'A NOUVEAU 2022', 0, 203370, 56, null, 1, 2, 1, 1);
INSERT INTO comptable_ecriturejournal(date, intitule, debit, credit, compte_general_id, compte_tiers_id, devise_id, journal_id, piece_id, exercice_id) VALUES ('2023-01-01', 'A NOUVEAU 2022', 26700, 0, 58, null, 1, 2, 1, 1);
INSERT INTO comptable_ecriturejournal(date, intitule, debit, credit, compte_general_id, compte_tiers_id, devise_id, journal_id, piece_id, exercice_id) VALUES ('2023-01-01', 'A NOUVEAU 2022', 172500, 0, 60, null, 1, 2, 1, 1);
INSERT INTO comptable_ecriturejournal(date, intitule, debit, credit, compte_general_id, compte_tiers_id, devise_id, journal_id, piece_id, exercice_id) VALUES ('2023-01-01', 'A NOUVEAU 2022', 0, 80000, 63, null, 1, 2, 1, 1);
INSERT INTO comptable_ecriturejournal(date, intitule, debit, credit, compte_general_id, compte_tiers_id, devise_id, journal_id, piece_id, exercice_id) VALUES ('2023-01-01', 'A NOUVEAU 2022', 300300, 0, 64, null, 1, 2, 1, 1);
INSERT INTO comptable_ecriturejournal(date, intitule, debit, credit, compte_general_id, compte_tiers_id, devise_id, journal_id, piece_id, exercice_id) VALUES ('2023-01-01', 'A NOUVEAU 2022', 0, 119560, 66, null, 1, 2, 1, 1);
INSERT INTO comptable_ecriturejournal(date, intitule, debit, credit, compte_general_id, compte_tiers_id, devise_id, journal_id, piece_id, exercice_id) VALUES ('2023-01-01', 'A NOUVEAU 2022', 18320, 0, 68, null, 1, 2, 1, 1);

-- Creation de l'entreprise --
INSERT INTO comptable_log(title, icon, content, color, date) VALUES ('Création de l''entreprise', 'fas fa-building', '', 'success', '2023-01-01');